# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYU5iQWpESdfymUYvq0SbfQlfJRpYSTQ
"""


import streamlit as st
import numpy as np
import pickle

# Load trained model (make sure model.pkl is in the same folder or path)
model = pickle.load(open('house_rent_model.pkl', 'rb'))

# --- Page Config ---
st.set_page_config(page_title="🏡 Rent Predictor", layout="centered")

# --- Custom CSS Styling ---
st.markdown("""
    <style>
    .main { background-color: #f5f7fa; }
    h1, h3, .stButton > button {
        font-family: 'Segoe UI', sans-serif;
    }
    .stButton > button {
        background-color: #ff4b4b;
        color: white;
        font-weight: bold;
        border-radius: 5px;
        padding: 0.5em 1em;
    }
    </style>
""", unsafe_allow_html=True)

# --- Title & Instructions ---
st.title("🏠 House Rent Price Prediction")
st.markdown("📋 *Enter the house details below to estimate the monthly rent:*")

# --- Input Form ---
col1, col2 = st.columns(2)

with col1:
    area = st.number_input("📐 Area (sq.ft)", min_value=100, step=10, value=250)
    bedrooms = st.slider("🛏️ Bedrooms", 1, 10, 3)
    floors = st.slider("🏢 Floors", 1, 5, 2)
    garage = st.selectbox("🚗 Garage", ["Yes", "No"])

with col2:
    bathrooms = st.slider("🛁 Bathrooms", 1, 10, 3)
    year_built = st.number_input("🏗️ Year Built", min_value=1900, max_value=2025, value=2000)
    location = st.selectbox("📍 Location", ["Downtown", "Suburban", "Rural", "Town"])
    condition = st.selectbox("🏚️ Condition", ["Excellent", "Good", "Fair", "Poor"])

# --- Encoding Maps ---
location_map = {"Downtown": 0, "Rural": 1, "Suburban": 2, "Town": 3}
condition_map = {"Excellent": 0, "Fair": 1, "Good": 2, "Poor": 3}
garage_map = {"Yes": 1, "No": 0}

# --- Predict Button ---
if st.button("🎯 Predict Rent"):
    features = np.array([[area, bedrooms, bathrooms, floors, year_built,
                          location_map[location], condition_map[condition], garage_map[garage]]])
    prediction = model.predict(features)[0]
    st.success(f"✅ Estimated Monthly Rent: ₹ {int(prediction):,}")

# --- Footer ---
st.markdown("---")
st.markdown(
    "<center><small style='color:gray;'>Made with ❤️ by Dhana Lakshmi | Powered by Streamlit & Scikit-learn</small></center>",
    unsafe_allow_html=True
)
