# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n2bkODxCZAN6SdzyGf170gv8GRiCVg50
"""

#!pip install streamlit

import streamlit as st
import numpy as np
import pickle

with open('house_rent_model.pkl','rb') as file:
  model = pickle.load(file)

st.title('🏠 House Rent Price Prediction')

st.markdown('Enter the house details below to estimate the rent:')

area = st.number_input("Area (sq.ft)", min_value=100, step=10)
bedrooms = st.slider("Number of Bedrooms", 1, 10, 2)
bathrooms = st.slider("Number of Bathrooms", 1, 10, 2)
floors = st.slider("Number of Floors", 1, 5, 1)
year_built = st.number_input("Year Built", min_value=1900, max_value=2025, value=2000)

location = st.selectbox("Location", ["Downtown", "Suburban", "Rural", "Town"])
condition = st.selectbox("Condition", ["Excellent", "Good", "Fair", "Poor"])
garage = st.selectbox("Garage", ["Yes", "No"])

location_map = {"Downtown": 0, "Rural": 1, "Suburban": 2, "Town": 3}
condition_map = {"Excellent": 0, "Fair": 1, "Good": 2, "Poor": 3}
garage_map = {"Yes": 1, "No": 0}

if st.button("Predict Rent"):
    features = np.array([[area, bedrooms, bathrooms, floors, year_built,
                          location_map[location], condition_map[condition], garage_map[garage]]])

    prediction = model.predict(features)[0]
    st.success(f"✅ Estimated Monthly Rent: ₹ {int(prediction):,}")

st.markdown("---")
st.markdown(
    "<small style='color:gray;'>Made with ❤️ by Dhana Lakshmi | Powered by Streamlit & Scikit-learn</small>",
    unsafe_allow_html=True
)